# Generated by Django 4.2 on 2023-05-23 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_and_user_management', '0001_initial'),
        ('counterparty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('signed_date', models.DateTimeField()),
                ('last_updated_date', models.DateTimeField()),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_industry', models.CharField(max_length=255)),
                ('contract_document_path', models.TextField()),
                ('qa_template_file_path', models.TextField()),
                ('contract_uploaded_source', models.CharField(max_length=12)),
                ('meta_tag_document_path', models.TextField()),
                ('contract_name', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('contract_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. Contract',
            },
        ),
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('contract_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_status', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '8. ContractStates',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('contract_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': '2. ContractType',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '7. Country',
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('contract_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_template_name', models.CharField(max_length=50)),
                ('contract_template_doc_file_path', models.TextField()),
                ('qa_template_file_path', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttype')),
            ],
            options={
                'verbose_name_plural': '1. ContractTemplate',
            },
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('contract_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=5)),
                ('contract_document_path', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('qa_template_file_path', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
            options={
                'verbose_name_plural': '9. ContractHistory',
            },
        ),
        migrations.CreateModel(
            name='ContractCounterparty',
            fields=[
                ('contract_counterparty_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterparty.counterparty')),
            ],
            options={
                'verbose_name_plural': '6. ContractCounterparty',
            },
        ),
        migrations.CreateModel(
            name='ContractAuthor',
            fields=[
                ('contract_author_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('remarks', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. ContractAuthor',
            },
        ),
        migrations.CreateModel(
            name='ContractAttachment',
            fields=[
                ('contract_attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.TextField()),
                ('attachment_name', models.CharField(max_length=50)),
                ('uploaded_date', models.DateTimeField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. ContractAttachment',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contractstatus'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttemplate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contracttype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.country'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_and_user_management.customer'),
        ),
    ]
